apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express-ingress
  namespace: default
  annotations:
    haproxy.org/check: "disabled"
    haproxy.org/backend-config-snippet: |
      no option httpchk
spec:
  ingressClassName: haproxy
  rules:
    - host: mongo-k8s.thekor.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mongo-express-service
                port:
                  number: 8081
