apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-hetzner
  namespace: cert-manager
spec:
  acme:
    email: technik@adata.de
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-hetzner-key
    solvers:
    - dns01:
        webhook:
          groupName: acme.adata.de
          solverName: hetzner
          config:
            secretName: hetzner-dns-api-token
            zoneName: adata.de
            apiUrl: https://dns.hetzner.com/api/v1
