apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy
  namespace: haproxy-controller
  annotations:
    spec.ingressClassName: "haproxy"
spec:
  rules:
    - host: app.com
      http:
        paths:
        - path: /
          pathType: Exact
          backend:
            service:
              name: mongo-express-service
              port:
                number: 8081
