apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chirpy-pvc
  namespace: chirpy
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
